# Valid database table names
SENSORS: [messages, calls, battery]

# Participants to include in the analysis
# You must create a file for each participant
# named pXXX containing their device_id
PIDS: [p01, p02]

# Global var with common day segments
DAY_SEGMENTS: &day_segments
  [daily, morning, afternoon, evening, night]

# Download data config
DOWNLOAD_DATASET:
  GROUP: AAPECS

# Readable datetime config
READABLE_DATETIME:
  FIXED_TIMEZONE: EST

# Communication SMS features config
COM_SMS:
  SMS_TYPES : [received, sent]
  DAY_SEGMENTS: *day_segments
  METRICS: [count, distinctcontacts]

# Communication call features config
# Separate configurations for missed and taken calls
COM_CALL:
  CALL_TYPE_MISSED : [missed]
  CALL_TYPE_TAKEN : [incoming, outgoing]
  DAY_SEGMENTS: *day_segments
  METRICS_MISSED: [count, distinctcontacts]
  METRICS_TAKEN: [count, distinctcontacts, meanduration, sumduration, hubermduration, varqnduration, entropyduration]