# Valid database table names
SENSORS: [applications_crashes, applications_foreground, applications_notifications, battery, bluetooth, calls, locations, messages, plugin_ambient_noise, plugin_device_usage, plugin_google_activity_recognition, screen]

# Participants to include in the analysis
# You must create a file for each participant
# named pXXX containing their device_id
PIDS: [p01, p02]

# Global var with common day segments
DAY_SEGMENTS: &day_segments
  [daily, morning, afternoon, evening, night]

# Global timezone
TIMEZONE: &timezone
  EST

# Download data config
DOWNLOAD_DATASET:
  GROUP: AAPECS

# Readable datetime config
READABLE_DATETIME:
  FIXED_TIMEZONE: *timezone

# Communication SMS features config
COM_SMS:
  SMS_TYPES : [received, sent]
  DAY_SEGMENTS: *day_segments
  METRICS: [count, distinctcontacts]

# Communication call features config
# Separate configurations for missed and taken calls
CALLS:
  TYPES: [missed, incoming, outgoing]
  METRICS:
    missed:  [count, distinctcontacts]
    incoming: [count, distinctcontacts, meanduration, sumduration, hubermduration, varqnduration, entropyduration]
    outgoing: [count, distinctcontacts, meanduration, sumduration, hubermduration, varqnduration, entropyduration]
  DAY_SEGMENTS: *day_segments

PHONE_VALID_SENSED_DAYS:
  BIN_SIZE: 5 # (in minutes)
  MIN_VALID_HOURS: 20 # (out of 24)
  MIN_BINS_PER_HOUR: 8 # (out of 60min/BIN_SIZE bins)

BARNETT_LOCATION:
  ACCURACY_LIMIT: 51 # filters location coordinates with an accuracy higher than this
  TIMEZONE: *timezone

BLUETOOTH:
  DAY_SEGMENTS: *day_segments
  METRICS: ["countscans", "uniquedevices", "countscansmostuniquedevice"]